spring.application.name=account-service
spring.datasource.url=jdbc:h2:file:/home/mahdi-frikha/Stage-Attijari/account-service/data/accountdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
api.key = 'sk-or-v1-ebd98d2d88e1489ffe0de702f5025aebdef2370f175a3d96cb7f3ea8df8aec70e'
